name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Renovate
        uses: renovatebot/github-action@6030949931ad2285e5e0fbe5101c2052c540262c # v26.21.7
        with:
          configurationFile: renovate/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}